# Generated by Django 4.1.7 on 2023-03-16 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Affiliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=25)),
                ('prenom', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=200)),
                ('num_tel', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=25)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=6)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=25)),
                ('prenom', models.CharField(max_length=25)),
                ('pseudo', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('num_tel', models.IntegerField()),
                ('date_naissance', models.DateField()),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id_admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='myapp.utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='infopreneur',
            fields=[
                ('id_infopreneur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='myapp.utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.contact')),
                ('id_produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.produit')),
                ('id_infopreneur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.infopreneur')),
            ],
        ),
        migrations.AddField(
            model_name='produit',
            name='id_infopreneur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.infopreneur'),
        ),
        migrations.CreateModel(
            name='Contrat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_affilie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.affiliation')),
                ('id_produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.produit')),
                ('id_infopreneur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.infopreneur')),
            ],
        ),
        migrations.AddField(
            model_name='contact',
            name='id_infopreneur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.infopreneur'),
        ),
    ]
