# Generated by Django 4.1.7 on 2023-03-23 11:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'Contactt',
            },
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=25)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=6)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('num_tel', models.IntegerField()),
                ('date_naissance', models.DateField()),
                ('image', models.ImageField(upload_to='')),
                ('user', models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id_admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='myapp.utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='infopreneur',
            fields=[
                ('id_infopreneur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='myapp.utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('reference', models.IntegerField(primary_key=True, serialize=False)),
                ('date_vente', models.DateField()),
                ('quantite', models.IntegerField()),
                ('id_contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.contact')),
                ('id_produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.produit')),
                ('id_infopreneur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.infopreneur')),
            ],
        ),
        migrations.AddField(
            model_name='produit',
            name='id_infopreneur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.infopreneur'),
        ),
        migrations.CreateModel(
            name='Contactt',
            fields=[
                ('id_c', models.IntegerField(primary_key=True, serialize=False)),
                ('id_infopreneur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.infopreneur')),
            ],
        ),
        migrations.CreateModel(
            name='Affilie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_affilie', models.IntegerField()),
                ('nom_affilie', models.CharField(max_length=30)),
                ('prenom_affilie', models.CharField(max_length=30)),
                ('contrat', models.TextField()),
                ('id_produit', models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='myapp.produit')),
                ('id_infopreneur', models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='myapp.infopreneur')),
            ],
        ),
    ]
