# Generated by Django 4.1.7 on 2023-03-23 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='affilie',
            name='id_affilie',
        ),
    ]
