# Generated by Django 4.2 on 2023-04-17 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='categorie',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
