# Generated by Django 4.1.7 on 2023-04-05 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='affilie',
            name='id_produit',
        ),
        migrations.AlterField(
            model_name='affilie',
            name='id_infopreneur',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='myapp.utilisateur'),
        ),
    ]
