# Generated by Django 4.2 on 2023-05-16 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='video',
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='subscription_type',
            field=models.CharField(choices=[('explorateur', 'Explorateur'), ('infopreneur', 'Infopreneur'), ('business', 'Business')], default='explorateur', max_length=20, null=True),
        ),
    ]
