# Generated by Django 4.2 on 2023-05-09 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_utilisateur_subscription_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='subscription_type',
            field=models.CharField(choices=[('explorateur', 'Explorateur'), ('infopreneur', 'Infopreneur'), ('business', 'Business')], default='explorateur', max_length=20, null=True),
        ),
    ]
