# Generated by Django 4.2 on 2023-04-19 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_contact_categorie'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormPopUp',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30, null=True)),
                ('description', models.TextField(null=True)),
                ('codeHtml', models.TextField(null=True)),
                ('URL', models.TextField(null=True)),
            ],
        ),
    ]
