# Generated by Django 4.1.7 on 2023-04-15 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_contactformsubmission'),
        ('myapp', '0002_remove_utilisateur_position'),
    ]

    operations = [
    ]
