# Generated by Django 4.2 on 2023-05-16 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_post_video_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affilie',
            name='contrat',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
