# Generated by Django 4.1.7 on 2023-04-12 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_contactformsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactformsubmission',
            name='phonenumber',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contactformsubmission',
            name='subject',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
