# Generated by Django 4.1.7 on 2023-04-10 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_utilisateur_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templatescommuns',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
