# Generated by Django 4.1.7 on 2023-03-23 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_affilie_id_affilie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='affilie',
            name='nom_affilie',
        ),
        migrations.RemoveField(
            model_name='affilie',
            name='prenom_affilie',
        ),
        migrations.AddField(
            model_name='affilie',
            name='contact',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='affilie',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='affilie',
            name='nom_prenom',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='affilie',
            name='pourcentage',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='affilie',
            name='contrat',
            field=models.TextField(null=True),
        ),
    ]
