# Generated by Django 4.1.7 on 2023-04-05 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_affilie_id_infopreneur'),
    ]

    operations = [
        migrations.AddField(
            model_name='affilie',
            name='id_produit',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='myapp.produit'),
        ),
        migrations.AlterField(
            model_name='affilie',
            name='id_infopreneur',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='myapp.infopreneur'),
        ),
    ]
