# Generated by Django 4.2 on 2023-04-20 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_formpopup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affilie',
            name='contrat',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
