# Generated by Django 4.1.7 on 2023-03-24 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_affilie_nom_affilie_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplatesCommuns',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30, null=True)),
                ('codeHtml', models.TextField(null=True)),
                ('type', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TemplatesUser',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30, null=True)),
                ('codeHtml', models.TextField(null=True)),
                ('type', models.CharField(max_length=30, null=True)),
                ('id_Commun', models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='myapp.templatescommuns')),
                ('id_infopreneur', models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='myapp.infopreneur')),
            ],
        ),
    ]
