# Generated by Django 4.2 on 2023-04-09 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_affilie_id_produit_alter_affilie_id_infopreneur'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='bio',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
