# Generated by Django 4.2 on 2023-05-26 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_post_id_infopreneur'),
    ]

    operations = [
        migrations.RenameField(
            model_name='utilisateur',
            old_name='subscription_type',
            new_name='Abonnement',
        ),
    ]
