# Generated by Django 4.1.7 on 2023-04-09 23:25

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_affilie_id_produit_alter_affilie_id_infopreneur'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplatesCommuns',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30, null=True)),
                ('codeHtml', models.CharField(max_length=30, null=True)),
                ('type', models.CharField(max_length=30, null=True)),
                ('image', models.ImageField(null=True, upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='affilie',
            name='contrat',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
