# Generated by Django 4.1.7 on 2023-03-25 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_templatescommuns_templatesuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatesuser',
            name='URL',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='templatesuser',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
