# Generated by Django 4.2 on 2023-04-10 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_utilisateur_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='templatescommuns',
            name='type',
        ),
    ]
