# Generated by Django 4.2 on 2023-04-20 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_affilie_contrat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='affilie',
            name='id_infopreneur',
        ),
        migrations.RemoveField(
            model_name='affilie',
            name='id_produit',
        ),
    ]
