# Generated by Django 4.1.7 on 2023-04-09 23:28

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_templatescommuns_alter_affilie_contrat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templatescommuns',
            name='codeHtml',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='date_naissance',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='num_tel',
            field=models.IntegerField(null=True),
        ),
    ]
