# Generated by Django 4.1.7 on 2023-03-27 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_templatesuser_url_templatesuser_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatescommuns',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='templatesuser',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
