# Generated by Django 4.2 on 2023-05-30 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_rename_subscription_type_utilisateur_abonnement'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Categorie',
            field=models.CharField(choices=[('bien-être corps cœur esprit', 'Bien-être Corps Cœur Esprit'), ('développement personnel et spirituel', 'Développement Personnel et Spirituel'), ('coaching professionnel et relationnel', 'Coaching Professionnel et Relationnel')], default='bien-être corps cœur esprit', max_length=80, null=True),
        ),
    ]
