# Generated by Django 4.2 on 2023-04-21 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_affilie_id_infopreneur_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formpopup',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
